language: node_js
node_js:
  - "6.9.1"
  - "iojs-v3"
sudo: false
cache: yarn
before_install: if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
